# lightning.pytorch==2.4.0
seed_everything: true
tags:
  exp: &exp c2i_wandb_100step
torch_hub_dir: null
huggingface_cache_dir: null
trainer:
  default_root_dir: ./workdirs
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: pixnerd-c2i
        name: *exp
  num_sanity_val_steps: 0
  max_steps: 200000
  val_check_interval: 100
  check_val_every_n_epoch: null
  log_every_n_steps: 10
  deterministic: null
  inference_mode: true
  use_distributed_sampler: false
  callbacks:
    - class_path: src.callbacks.model_checkpoint.CheckpointHook
      init_args:
        every_n_train_steps: 100
        save_top_k: -1
        save_last: true
    - class_path: src.callbacks.save_images.SaveImagesHook
      init_args:
         save_dir: val
         save_compressed: false
         log_preview: true
         preview_max_images: 16
         preview_ncols: 4
  plugins:
    - src.plugins.bd_env.BDEnvironment
model:
  vae:
    class_path: src.models.autoencoder.pixel.PixelAE
    init_args:
       scale: 1.0
  denoiser:
    class_path: src.models.transformer.pixnerd_c2i.PixNerDiT
    init_args:
        in_channels: 3
        patch_size: 16
        num_groups: 16
        hidden_size: &hidden_dim 1152
        hidden_size_x: 64
        num_blocks: 30
        num_cond_blocks: 26
        nerf_mlpratio: 2
        num_classes: &num_classes 10
  conditioner:
    class_path: src.models.conditioner.class_label.LabelConditioner
    init_args:
      num_classes: *num_classes
  diffusion_trainer:
    class_path: src.diffusion.flow_matching.training_repa.REPATrainer
    init_args:
      lognorm_t: true
      encoder:
        class_path: src.models.encoder.DINOv2
        init_args:
          weight_path: /path/to/dinov2_vitb14
      align_layer: 8
      proj_denoiser_dim: *hidden_dim
      proj_hidden_dim: *hidden_dim
      proj_encoder_dim: 768
      scheduler: &scheduler src.diffusion.flow_matching.scheduling.LinearScheduler
  diffusion_sampler:
    class_path: src.diffusion.flow_matching.sampling.EulerSampler
    init_args:
      num_steps: 100
      guidance: 3.5
      guidance_interval_min: 0.1
      guidance_interval_max: 1.0
      scheduler: *scheduler
      w_scheduler: src.diffusion.flow_matching.scheduling.LinearScheduler
      guidance_fn: src.diffusion.base.guidance.simple_guidance_fn
      step_fn: src.diffusion.flow_matching.sampling.ode_step_fn
  ema_tracker:
    class_path: src.callbacks.simple_ema.SimpleEMA
    init_args:
      decay: 0.9999
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-4
      weight_decay: 0.0
data:
  train_dataset:
    class_path: src.data.dataset.imagenet.PixImageNet
    init_args:
      root: datasets/imagenette2-320/train
      resolution: 256
  eval_dataset:
    class_path: src.data.dataset.randn.ClassLabelRandomNDataset
    init_args:
      num_classes: *num_classes
      max_num_instances: 128
      latent_shape:
        - 3
        - 256
        - 256
  pred_dataset:
    class_path: src.data.dataset.randn.ClassLabelRandomNDataset
    init_args:
      num_classes: *num_classes
      max_num_instances: 128
      latent_shape:
        - 3
        - 256
        - 256
  train_batch_size: 16
  train_num_workers: 4
  pred_batch_size: 16
  pred_num_workers: 1
